version: '3.8'

services:
  eos_connect:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped