version: '3.8'

services:
  eos_connect:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/ohand/eos_connect:snapshot
    ports:
      - "8081:8081"
    volumes:
      - ./src/config.yaml:/app/config.yaml
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped