name: feature - build image and push
# This workflow builds and pushes a Docker image to GitHub Container Registry.
# It is triggered on pushes to branches other than "main" and "develop", and can also be triggered manually.
# The image is tagged with the branch name of the push event.
# The workflow uses the GITHUB_TOKEN secret for authentication with GitHub Container Registry.

on:
  push:
    branches-ignore:
      - "main"
      - "develop"
  workflow_dispatch: # allows manual triggering of the workflow

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert repository owner to lowercase
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.owner }}/eos_connect
          tags: |
            type=raw,value=feature_dev_${{ github.ref_name }}
          labels: |
            org.opencontainers.image.title=EOS Connect
            org.opencontainers.image.description=Open-source tool for intelligent energy management and optimization. Latest commit: ${{ github.event.head_commit.message }}
            org.opencontainers.image.source=https://github.com/ohAnd/EOS_connect
            org.opencontainers.image.documentation=https://github.com/ohAnd/EOS_connect#readme
            org.opencontainers.image.vendor=ohAnd
            org.opencontainers.image.licenses=MIT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=feature_dev_${{ github.ref_name }}
            COMMIT_SHA=${{ github.sha }}
            COMMIT_MESSAGE=${{ github.event.head_commit.message }}
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
