name: feature - build image and push
# This workflow builds and pushes a Docker image to GitHub Container Registry.
# It is triggered on pushes to branches other than "main" and "develop", and can also be triggered manually.
# The image is tagged with the branch name of the push event.
# The workflow uses the GITHUB_TOKEN secret for authentication with GitHub Container Registry.

on:
  push:
    branches-ignore:
      - "main"
      - "develop"
  workflow_dispatch: # allows manual triggering of the workflow

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert repository owner to lowercase
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build image
        run: docker build -t ghcr.io/${{ env.owner }}/eos_connect:feature .

      # Only run tagging and pushing tasks for "push" events
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag image with develop version
        run: docker tag ghcr.io/${{ env.owner }}/eos_connect:feature ghcr.io/${{ env.owner }}/eos_connect:feature_dev_${{ github.ref_name }}

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ env.owner }}/eos_connect:feature_dev_${{ github.ref_name }}
